### ISSUE TITLE
报错很多呀

### ISSUE THREAD

**Issue by Ray-56** [soraping/redux-observable-boilerplate#1]
![image](https://user-images.githubusercontent.com/17818179/67852046-a8d00b80-fb46-11e9-9273-ec69ffe969e7.png)
![image](https://user-images.githubusercontent.com/17818179/67852067-b1c0dd00-fb46-11e9-8072-04838ada9bf3.png)
类型很多错误

**Comment by soraping** [comment]
刚跑了下，并没有发现有类型错误的情况，你可以查阅下ts的配置文件以及一些关键模块的版本信息

**Comment by Ray-56** [comment]
难道是`"typesafe-actions": "^5.1.0-1",`版本不同的问题？

![image](https://user-images.githubusercontent.com/17818179/67853211-ff3e4980-fb48-11e9-9e33-fc091986a3e1.png)
这里action类型为never，很奇怪

**Comment by Ray-56** [comment]
确定是`typesafe-actions`版本的问题，更改为 v4 就不是 `never`了
